language: python

matrix:
  include:
      - os: linux
        sudo: required
        python: 2.7
        env: TOXENV=py27
      - os: osx
        language: generic
        env: TOXENV=py27

# Install test dependencies. TravisCI gives us nose, mock, and pytest by default
install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - "coverage run --source=uiautomator setup.py nosetests"
  - "python setup.py sdist"

after_success:
  coveralls
